### ISSUE TITLE
Upgrade to use Acorn v2

### ISSUE THREAD

**Issue by moll** [substack/node-detective#52]
Hey,

I'm getting some parse errors when running [dependency-check](https://github.com/maxogden/dependency-check), which uses detective, on my files. Before digging further, I noticed Acorn is now at v2, but Detective still on v1. Perhaps upgrading to v2 would solve things without debugging. :-)

Cheers

**Comment by sevenseacat** [comment]
Oh yes, I'm having a multitude of Acorn-related problems when used with Bower...

**Comment by deathcap** [comment]
👍 Acorn 2 (also used by @substack's [syntax-error](https://www.npmjs.com/package/syntax-error), acorn@2.7.0, versus node-detective using the ancient acorn@1.2.2) in particular includes this important fix:

https://github.com/ternjs/acorn/commit/aed55f3881beb1ea26d8622ada9973839b2b7175 Use regexps instead of magic generated functions Remove need for acorn_csp.js

Without it, acorn's identifier.js use of `new Function()` violates the `unsafe-eval` Content-Security-Policy:

acorn.js:1576Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".

which is the default CSP in Chrome browser extensions (see https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval, supposedly can be relaxed with `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`). This breaks Chrome apps embedding acorn@1, therefore detective@4.3.1, therefore browserify@13.0.0 (currently the latest).

**Comment by FallingSnow** [comment]
Please merge this, browserify doesn't work as a module because of the above error.
